package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/DoplexLabs/belay-engine/internal/localapp"
	"github.com/DoplexLabs/belay-engine/internal/telemetry"
)

// sendTelemetryActivity is Belay's only product-telemetry call. It is a
// variable so command tests never touch the network.
var sendTelemetryActivity = func(ctx context.Context, root string, stderr io.Writer) {
	client := telemetry.New(root, buildVersion, telemetry.WithNotice(stderr))
	sendCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if _, err := client.RecordActivity(sendCtx); err != nil && stderr != nil {
		fmt.Fprintf(stderr, "belay: usage ping skipped (%s)\n", err.Error())
	}
}

func startTelemetryActivity(ctx context.Context, root string, stderr io.Writer) {
	go sendTelemetryActivity(ctx, root, stderr)
}

func runTelemetry(ctx context.Context, args []string, stdout, stderr io.Writer) error {
	_ = ctx
	flags := flag.NewFlagSet("telemetry", flag.ContinueOnError)
	flags.SetOutput(stderr)
	home := flags.String("home", "", "Belay Local state directory (default BELAY_HOME or ~/.belay)")
	flags.Usage = func() {
		fmt.Fprintln(stderr, `usage: belay telemetry [status|on|off] [--home DIR]

Belay sends a de-identified install ping once and an "active" ping at most
once per day. The payload is exactly: schema_version, event, a random
telemetry_id generated by Belay, version, os, arch, which of
claude/codex/cursor are installed, and sent_at. No paths, prompts, transcripts,
project names, or account identity are ever sent. The receiver keeps the request's country, not
its address, and forwards the same fields to a hosted analytics processor
keyed by the random ID. "off" stops it; BELAY_TELEMETRY=0 or DO_NOT_TRACK=1
also work.`)
	}
	action := "status"
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		action = args[0]
		args = args[1:]
	}
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("telemetry accepts one action: status, on, or off")
	}
	paths, err := localapp.ResolvePaths(*home)
	if err != nil {
		return err
	}
	client := telemetry.New(paths.Root, buildVersion)
	switch action {
	case "status":
	case "on":
		if err := client.SetOptOut(false); err != nil {
			return err
		}
	case "off":
		if err := client.SetOptOut(true); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unknown telemetry action %q", action)
	}
	return writeJSON(stdout, client.Status())
}
